org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.user.home=D:/AndroidHome
systemProp.user.home=D:/AndroidHome
systemProp.android.user.home=D:/AndroidHome
android.overridePathCheck=true
org.gradle.project.android.user.home=D:/AndroidHome
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
